### ISSUE TITLE
Data links broken

### ISSUE THREAD

**Issue by cajun1689** [ektf1130/high-throughput-plant-phenotyping-system#1]
looks like the data links for your images are broken is there any chance of being able to fix it?

**Comment by ektf1130** [comment]
> looks like the data links for your images are broken is there any chance of being able to fix it?


Hello, cajun1689  
I updated the link. 
Also, you can download at https://drive.google.com/file/d/12qC5B3gAJy-VWki8kkWf_4gtzBcU-HIO/view?usp=sharing 
Thank you.
